set nocompatible
set nobackup

map <esc>OA <Up>
map <esc>OB <Down>
map <esc>OC <Right>
map <esc>OD <Left>
map! <esc>OA <Up>
map! <esc>OB <Down>
map! <esc>OC <Right>
map! <esc>OD <Left>


set backspace=start,eol,indent

set encoding=utf-8
filetype plugin indent on
syntax enable
set cindent
set ruler
set number
