set nocompatible
set nobackup

map <esc>OA <Up>
map <esc>OB <Down>
map <esc>OC <Right>
map <esc>OD <Left>
map! <esc>OA <Up>
map! <esc>OB <Down>
map! <esc>OC <Right>
map! <esc>OD <Left>


set backspace=start,eol,indent

set encoding=utf-8
filetype plugin indent on
set clipboard=unnamed,autoselect
syntax enable
set cindent
set autoindent
set smartindent
set cursorline
set ruler
set number
set showcmd

set list
set listchars=tab:>_,trail:_
highlight IGSpace ctermbg=Red guibg=Red
match IGSpace /　/

set smartcase
set hlsearch
set showmatch


set visualbell
