#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Default Editor
export EDITOR=nano
export VISUAL=$EDITOR

# Enable color support
alias ls='ls --color=auto --show-control-chars'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#aliases
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -la'
alias l='ls -CF'
alias c='clear'
alias e='echo -e'
alias x='exit'
alias k='kill'

alias myip='wget http://ipinfo.io/ip -qO -'

PS1='[\u@\h \W]\$ '
