if [ "$ZDOTDIR" = "" ]
then
  ZDOTDIR="~"
fi

# Import from ZDOTDIR/zshrc.d/*.sh
setopt nonomatch
for i in "$ZDOTDIR"/zshrc.d/*.sh ; do
    if [ -r "$i" ]; then
        source "$i"
    fi
done
setopt nomatch

#PROMPT
PROMPT='%B%F{green}%n@%m%f%b:%B%F{blue}%~%f%b%# '

#KEYMAP
bindkey "^[[3~" delete-char

# History
HISTFILE=$ZDOTDIR/.zsh_history
HISTSIZE=2000
SAVEHIST=2000
setopt share_history
setopt histignorealldups

autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end


# Completion
autoload -Uz compinit
compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# Enable color support
alias dir='dir --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

#aliases
alias ll='ls -l'
alias la='ls -A'
alias lla='ls -la'
alias l='ls -CF'
alias md='mkdir'
alias c='clear'
alias e='echo -e'
alias x='exit'
alias k='kill'

# auto cd
setopt auto_cd

#cd aliases
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../z..'
alias .......='cd ../../../../../..'

# if ps supports --sort, use it.
if ps --sort=start_time 2>/dev/null 1>/dev/null; then
  alias ps='ps --sort=start_time'
fi

# use gnu ls if available.
# if ls supports --show-control-chars, use it.
if type gls 2>/dev/null 1>/dev/null; then
  if gls --show-control-chars 2>/dev/null 1>/dev/null; then
    alias ls='gls --color=auto --show-control-chars'
  else
    alias ls='gls'
  fi
elif ls --show-control-chars 2>/dev/null 1>/dev/null; then
	alias ls='ls --color=auto --show-control-chars'
fi

# use gnu grep if available.
if type ggrep 2>/dev/null 1>/dev/null; then
  alias grep='ggrep'
fi

# use gnu find if available.
if type gfind 2>/dev/null 1>/dev/null;then
  alias find='gfind'
fi

# use gnu sed if available.
if type gsed 2>/dev/null 1>/dev/null; then
  alias sed='gsed'
fi

# use gnu awk if available.
if type gawk 2>/dev/null 1>/dev/null; then
  alias awk='gawk'
fi

# use gnu date if available.
if type gdate 2>/dev/null 1>/dev/null; then
  alias date='gdate'
fi

# use gnu readlink if avaliable.
if type greadlink 2>/dev/null 1>/dev/null; then
  alias readlink='greadlink'
fi

# use gnu xargs if available.
if type gxargs 2>/dev/null 1>/dev/null; then
  alias xargs='gxargs'
fi

# myip command
if type wget 2>/dev/null 1>/dev/null; then
	alias myip='wget http://ipinfo.io/ip -qO -'
fi

if type curl 2>/dev/null 1>/dev/null; then
	alias myip='curl http://ipinfo.io/ip'
fi

function mkcd() {
  if [[ -d $1 ]]; then
    echo "$1 already exists!"
    cd $1
  else
    mkdir -p $1 && cd $1
  fi
}

# ~/bin to PATH
if [ -e "${HOME}/bin" ]
then
	export PATH=${HOME}/bin:$PATH
fi